import { v4 as uuid } from 'uuid';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: 'Cauliflower',
    imageSrc: ['/Assets/products/cauliflower.jpg'],
    price: 250,
    quantity: '1 kg',
    inStock: true,
    rating: 3,
    categoryName: 'vegetable',
    discount: 15,
  },
  {
    _id: uuid(),
    title: 'Green-Peas',
    imageSrc: ['/Assets/products/green-peas.jpg'],
    price: 144,
    quantity: '1 kg',
    inStock: true,
    rating: 4,
    categoryName: 'vegetable',
    discount: 4,
  },
  {
    _id: uuid(),
    title: 'Sapodta',
    imageSrc: ['/Assets/products/sapodilla.jpg'],
    price: 96,
    quantity: '500 g',
    inStock: true,
    rating: 3,
    categoryName: 'fruit',
    discount: 4,
  },
  {
    _id: uuid(),
    title: 'Coconut',
    imageSrc: ['/Assets/products/coconut.jpg'],
    price: 23,
    quantity: '1 pc',
    inStock: true,
    rating: 2,
    categoryName: 'fruit',
    discount: 3,
  },
  {
    _id: uuid(),
    title: 'Egg',
    imageSrc: ['/Assets/products/egg.jpg'],
    price: 75,
    quantity: '12 pcs',
    inStock: true,
    rating: 1,
    categoryName: 'egg and meat',
    discount: 6,
  },
  {
    _id: uuid(),
    title: 'BoneLess chicken',
    imageSrc: ['/Assets/products/boneless.jpg'],
    price: 214.7,
    quantity: '1 kg',
    inStock: true,
    rating: 1,
    categoryName: 'egg and meat',
    discount: 10,
  },
  {
    _id: uuid(),
    title: 'Wheat Sharbati',
    imageSrc: ['/Assets/products/wheat.jpg'],
    price: 56,
    quantity: '1 kg',
    inStock: true,
    rating: 3,
    categoryName: 'grain',
    discount: 5,
  },
  {
    _id: uuid(),
    title: 'Salt',
    imageSrc: ['/Assets/products/salt.jpg'],
    price: 15,
    quantity: '1 kg',
    inStock: true,
    rating: 4,
    categoryName: 'grain',
    discount: 2,
  },
];
